# Generated by Django 4.1.6 on 2023-02-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_new_description_alter_new_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='time',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
