# Generated by Django 4.1.6 on 2023-02-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_time_new_date_new_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='banner',
        ),
    ]
