# Generated by Django 4.1.6 on 2023-02-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_new_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='description',
        ),
    ]
