# Generated by Django 4.1.6 on 2023-02-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_new_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='subtitle',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
